package io.overtimecoder.eic;

import net.minecraftforge.fml.common.ModMetadata;

public class ModInfo {
    public static void loadInfo(ModMetadata meta) {
        meta.modId = EIC.MODID;
        meta.name = EIC.NAME;
        meta.description ="Electric Industry Craft";
        meta.version =EIC.VERSION ;
        meta.updateJSON="https://raw.githubusercontent.com/OvertimeCoder/EIC/main/version/EICVersionCheck.json";
        meta.url = "https://github.com/OvertimeCoder/EIC";
        meta.authorList.add("Overtime Coder");
        meta.credits = "";
        meta.logoFile ="";
        meta.autogenerated = false;
    }
}
